// Generated by CoffeeScript 1.4.0
(function() {
  var browserAction, delay, flag, onClick, reloadTabs, tabs, timeoutID, windows;

  browserAction = chrome.browserAction, windows = chrome.windows, tabs = chrome.tabs;

  delay = 300;

  timeoutID = null;

  flag = false;

  reloadTabs = function($tabs) {
    var item, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = $tabs.length; _i < _len; _i++) {
      item = $tabs[_i];
      _results.push(tabs.reload(item.id));
    }
    return _results;
  };

  onClick = function($double) {
    return windows.getCurrent({
      populate: true
    }, function($window) {
      var item, pinnedList, unpinnedList;
      pinnedList = (function() {
        var _i, _len, _ref, _results;
        _ref = $window.tabs;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          if (item.pinned) {
            _results.push(item);
          }
        }
        return _results;
      })();
      unpinnedList = $window.tabs.slice(pinnedList.length);
      if (pinnedList.length) {
        return reloadTabs($double ? unpinnedList : pinnedList);
      } else {
        return reloadTabs(unpinnedList);
      }
    });
  };

  browserAction.onClicked.addListener(function() {
    if (flag) {
      onClick(true);
    }
    clearTimeout(timeoutID);
    timeoutID = setTimeout(function($double) {
      if (!$double) {
        onClick(false);
      }
      return flag = false;
    }, delay, flag);
    return flag = true;
  });

}).call(this);
